version: '3.3'

services:
  fastapi_app:
    build: './'
    ports:
      - 8000:8000
    depends_on:
      - mongodb_container
  mongodb_container:
    image: mongo:latest
    ports:
      - "27017:27017"

